name: Deploy Backend to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'  # Trigger deployment only when changes occur in the `backend` folder

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.x'  # Adjust Node.js version based on your project requirements

    - name: Install dependencies
      run: |
        cd backend
        npm install

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: tobedone-be
        slot-name: production
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: ./backend
