name: Deploy Backend to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'  # Trigger deployment only when changes occur in the `backend` folder

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.x'  # Adjust Node.js version based on your project requirements

    - name: Install dependencies
      run: |
        cd backend
        npm install

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: tobedone-be  # Replace with your Azure App Service name
        slot-name: production
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: './backend'  # Ensure only the backend folder is used for deployment
        app-directory: './backend'  # Make sure it points to the backend directory
